### PR TITLE
adding redux

### PR DESCRIPTION
**Pull request by rotshidzw**
👍 made sure that  i keep state immutable in reducers
👍changed  the default state in my books reducer from an empty array to an array with a few books
👍 Connected my app to the Redux store.

### CODE REVIEW

**Review by rloterh — CHANGES_REQUESTED** [review]
Hi Rotshidzwa, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow. Kindly note that the gitflow of this project should have merge request **from feature into development**.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by rotshidzw** [comment]
> Hi Rotshidzwa,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that has incorrect gitflow. Kindly note that the gitflow of this project should have merge request **from feature into development**.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

how    can you clarify

**Comment by Whoistolu** [comment]
> > Hi Rotshidzwa,
> > While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> > ## Invalid Code Review Request
> > You have submitted a project, that has incorrect gitflow. Kindly note that the gitflow of this project should have merge request **from feature into development**.
> > Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
> > Cheers and Happy coding!clapclapclap
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > _Invalid Code Review Request **does not count** into the code reviews limit._
> 
> how can you clarify

Hello @rotshidzw , currently your merge request is from the `feature(redux)` into `master` instead of a merge request from the `feature(redux)` into `development`. I am clarifying this on behalf of the previous reviewer. Kindly fix the git-flow. Some part of your project requirements states that you should make sure that you used the correct flow [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).

**Review by Whoistolu — COMMENTED** [review]
Hi @rotshidzw 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

As stated by the previous reviewer: You have submitted a project, that has incorrect gitflow. Kindly note that the gitflow of this project should have merge request from feature into development.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
